language: python
python:
  - "2.6"
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - "export DISPLAY=:99.0" # Should fix matplotlib errors
    - "sh -e /etc/init.d/xvfb start"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2 ordereddict; fi
      #- sudo bash -c "umask 0002"
    - sudo python setup.py install_system_packages
    - python setup.py install
script:
    - nosetests ngs_mapper/tests -v --nologcapture
